---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: kube-prometheus-stack
spec:
  releaseName: kube-prometheus-stack
  chart:
    spec:
      chart: kube-prometheus-stack
      sourceRef:
        kind: HelmRepository
        name: kube-prometheus-stack
        namespace: infrastructure
  values:
    prometheus-node-exporter:
      hostRootFsMount:
        enabled: false
  interval: 1h0m0s
  install:
    remediation:
      retries: 3
